/*
* 此配置文件为系统使用，请勿修改，否则可能无法正常使用
*
* 如需自定义配置请复制修改上一级help_default.js
*
* */

export const helpCfg = {
  // 帮助标题
  title: 'TRSS虚空帮助',

  // 帮助副标题
  subTitle: 'TRSS-Yunzai & trss-akasha-terminal-plugin',

  // 帮助表格列数，可选：2-5，默认3
  // 注意：设置列数过多可能导致阅读困难，请参考实际效果进行设置
  colCount: 4,

  // 单列宽度，默认265
  // 注意：过窄可能导致文字有较多换行，请根据实际帮助项设定
  colWidth: 265,

  // 皮肤选择，可多选，或设置为all
  // 皮肤包放置于 resources/help/theme
  // 皮肤名为对应文件夹名
  // theme: 'all', // 设置为全部皮肤
  // theme: ['default','theme2'], // 设置为指定皮肤
  theme: 'all',

  // 排除皮肤：在存在其他皮肤时会忽略该项内设置的皮肤
  // 默认忽略default：即存在其他皮肤时会忽略自带的default皮肤
  // 如希望default皮肤也加入随机池可删除default项
  themeExclude: ['default'],

  // 是否启用背景毛玻璃效果，若渲染遇到问题可设置为false关闭
  bgBlur: true
}

// 帮助菜单内容
export const helpList = [{
  group: '决斗!抽卡系统',
  list: [{
    icon: 19,
    title: '#虚空做委托',
    desc: '每日委托，获得纠缠之缘'
}, {
    icon: 20,
    title: '#虚空(十连)抽武器',
    desc: '花费纠缠之缘抽取武器。提升战力'
  }, {
    icon: 20,
    title: '#我的武器',
    desc: '查看自己抽到的武器'
  }, {
    icon: 20,
    title: '#武器库',
    desc: '查看可以被抽到的武器'
  }]
}, {
  group: '一起决斗吧！！！',
  list: [{
    icon: 20,
    title: '#御前决斗@群友',
    desc: '和群友决斗吧，败者可是有惩罚的哦'
  }]
}, {
  group: '群友?老婆?!',
  list: [{
    icon: 20,
    title: '领取低保',
    desc: '钱太少可以使用'
  }, {
    icon: 20,
    title: '住所改名xxx',
    desc: '给家改名'
  }, {
    icon: 20,
    title: '看房',
    desc: '看看当前可买房产'
  }, {
    icon: 20,
    title: '买房+id(@群友)',
    desc: '给自己或群友购买房产,增加各类数值'
  }, {
    icon: 20,
    title: '上交存款+数量',
    desc: '将一部分钱上交给老婆'
  }, {
    icon: 20,
    title: '娶群友',
    desc: '随机娶一位群友做老婆'
  }, {
    icon: 20,
    title: '娶@群友',
    desc: '指定求婚'
  }, {
    icon: 20,
    title: '我愿意/拒绝@群友',
    desc: '回应群友的求婚'
  }, {
    icon: 20,
    title: '强娶@群友',
    desc: '强行娶走一位群友'
  }, {
    icon: 20,
    title: '抢老婆@群友',
    desc: '抢走对方的老婆!'
  }, {
    icon: 20,
    title: '闹离婚',
    desc: '将对方从你的老婆里删掉'
  }, {
    icon: 20,
    title: '甩掉@群友',
    desc: '让对方失去你这个老婆'
  }, {
    icon: 20,
    title: '退出/踢出银啪@群友',
    desc: '退出别人的银啪队伍或把别人踢出自己的队伍'
  }, {
    icon: 20,
    title: '打工赚钱',
    desc: '有些事,是需要代价的'
  }, {
    icon: 20,
    title: '逛街',
    desc: '出门解锁更多玩法和随机事件'
  }, {
    icon: 20,
    title: '我的彩票',
    desc: '查看当前购买的彩票'
  }, {
    icon: 20,
    title: '虚空彩球兑换',
    desc: '兑换当期奖励'
  }, {
    icon: 20,
    title: '抱抱@老婆',
    desc: '抱抱增加好感度'
  }, {
    icon: 20,
    title: '开始银啪',
    desc: '?'
  }, {
    icon: 20,
    title: '家庭信息',
    desc: '看看家,看看资产'
  }, {
    icon: 20,
    title: '虚空清除无效存档',
    desc: '部分指令无响应时使用'
  }]
}, {
  group: '虚空商城',
  list: [{
    icon: 30,
    title: '#虚空商城',
    desc: '查看虚空商城中的道具'
  }, {
    icon: 31,
    title: '#购买道具+编号',
    desc: '购买指定编号的道具'
  }, {
    icon: 32,
    title: '#我的虚空背包',
    desc: '查看自己拥有的道具'
  }, {
    icon: 33,
    title: '#使用道具+编号',
    desc: '使用指定编号的道具'
  }, {
    icon: 34,
    title: '#赠送道具+编号',
    desc: '将道具赠送给其他人'
  }, {
    icon: 35,
    title: '#道具详情+编号',
    desc: '查看道具的详细信息'
  }, {
    icon: 36,
    title: '#每日签到',
    desc: '每日签到获得奖励'
  }, {
    icon: 37,
    title: '#商城刷新',
    desc: '刷新商城中的道具'
  }]
}, {
  group: '虚空合成系统',
  list: [{
    icon: 40,
    title: '#合成列表',
    desc: '查看所有可合成的配方'
  }, {
    icon: 41,
    title: '#虚空合成+道具名',
    desc: '合成指定的道具'
  }, {
    icon: 42,
    title: '#我的工坊',
    desc: '查看自己的合成工坊信息'
  }, {
    icon: 43,
    title: '#升级工坊',
    desc: '升级合成工坊等级'
  }, {
    icon: 44,
    title: '#批量合成+道具名',
    desc: '批量合成指定道具'
  }, {
    icon: 45,
    title: '#分解道具+道具名',
    desc: '分解道具获得材料'
  }, {
    icon: 46,
    title: '#合成历史',
    desc: '查看合成制作记录'
  }]
}, {
  group: '任务系统',
  list: [{
    icon: 50,
    title: '#任务列表',
    desc: '查看所有可接取的任务'
  }, {
    icon: 51,
    title: '#每日任务',
    desc: '查看每日任务进度'
  }, {
    icon: 52,
    title: '#周常任务',
    desc: '查看每周任务进度'
  }, {
    icon: 53,
    title: '#特殊任务',
    desc: '查看特殊活动任务'
  }, {
    icon: 54,
    title: '#领取奖励+任务名',
    desc: '完成任务并领取奖励'
  }, {
    icon: 55,
    title: '#刷新任务',
    desc: '重置任务列表'
  }, {
    icon: 56,
    title: '#任务商店',
    desc: '查看任务积分兑换商店'
  }, {
    icon: 57,
    title: '#兑换+物品名',
    desc: '使用任务积分兑换物品'
  }]
}, {
  group: '情侣',
  list: [{
    icon: 60,
    title: '#约会',
    desc: '与伴侣进行约会活动'
  }, {
    icon: 61,
    title: '#情侣任务',
    desc: '查看情侣专属任务'
  }, {
    icon: 62,
    title: '#表白',
    desc: '向心仪的人表白'
  }, {
    icon: 63,
    title: '#求婚',
    desc: '向恋人求婚结婚'
  }, {
    icon: 64,
    title: '#情侣排行',
    desc: '查看情侣亲密度排行榜'
  }, {
    icon: 65,
    title: '#送礼物',
    desc: '给伴侣赠送礼物'
  }, {
    icon: 66,
    title: '#情侣决斗',
    desc: '情侣之间的决斗对战'
  }, {
    icon: 67,
    title: '#开设店铺',
    desc: '开设属于自己的店铺'
  }, {
    icon: 68,
    title: '#我的店铺',
    desc: '查看店铺经营信息'
  }, {
    icon: 69,
    title: '#升级店铺',
    desc: '升级店铺等级'
  }, {
    icon: 71,
    title: '#cp银行',
    desc: '存储爱心到情侣银行'
  }, {
    icon: 72,
    title: '#取爱心',
    desc: '从情侣银行提取爱心'
  }]
}, {
  group: '情侣打卡系统',
  list: [{
    icon: 80,
    title: '#情侣打卡',
    desc: '情侣每日打卡记录'
  }, {
    icon: 81,
    title: '#打卡记录',
    desc: '查看历史打卡记录'
  }, {
    icon: 82,
    title: '#设置纪念日+内容',
    desc: '添加重要的纪念日'
  }, {
    icon: 83,
    title: '#纪念日列表',
    desc: '查看所有纪念日'
  }, {
    icon: 84,
    title: '#删除纪念日+内容',
    desc: '删除指定的纪念日'
  }, {
    icon: 85,
    title: '#纪念日提醒',
    desc: '查看今日纪念日提醒'
  }]
}, {
  group: '管理命令，仅bot管理员可用',
  auth: 'master',
  list: [{
    icon: 91,
    title: '虚空重置时间',
    desc: '清除本群的时间记录,at则清除对方的'
  }, {
    icon: 92,
    title: '#虚空彩球开奖',
    desc: '顾名思义'
  }, {
    icon: 93,
    title: '#虚空更新',
    desc: '更新插件到最新版本'
  }, {
    icon: 94,
    title: '#虚空强制更新',
    desc: '强制更新插件'
  }, {
    icon: 95,
    title: '#虚空重启',
    desc: '重启虚空插件'
  }, {
    icon: 96,
    title: '#重置虚空配置',
    desc: '重置插件配置文件'
  }, {
    icon: 97,
    title: '#获取虚空配置',
    desc: '获取当前配置文件'
  }]
}, {
  group: '测试功能',
  auth: 'master',
  list: [{
    icon: 100,
    title: '#虚空cp文生成',
    desc: '本地生成cp文的（不太确定能不能用）'
  }]

}]
export const isSys = true
